export const genreList = [
   { genreName: "جنایی", genreTranslation: "Crime" },
   { genreName: "جنگی", genreTranslation: "War" },
   { genreName: "ماجرایی", genreTranslation: "Adventure" },
   { genreName: "معمایی", genreTranslation: "Mystery" },
   { genreName: "عاشقانه", genreTranslation: "Romance" },
   { genreName: "علمی تخیلی", genreTranslation: "Science Fiction" },
   { genreName: "موزیکال", genreTranslation: "Music" },
   { genreName: "ترسناک", genreTranslation: "Horror" },
   { genreName: "درام", genreTranslation: "Drama" },
   { genreName: "خانوادگی", genreTranslation: "Family" },
   { genreName: "تاریخی", genreTranslation: "History" },
   { genreName: "اکشن", genreTranslation: "Action" },
   { genreName: "کمدی", genreTranslation: "Comedy" },
   { genreName: "وسترن", genreTranslation: "Western" },
   { genreName: "مستند", genreTranslation: "Documentary" },
];
